/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iotc_control_channel_protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "iotc_control_channel_protocol.pb-c.h"
void iotc_client_ftest_fw__iotc_client_api____server_address__init(
    XiClientFtestFw__XiClientAPI__ServerAddress *message) {
  static XiClientFtestFw__XiClientAPI__ServerAddress init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____SERVER_ADDRESS__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__connect__init(
    XiClientFtestFw__XiClientAPI__Connect *message) {
  static XiClientFtestFw__XiClientAPI__Connect init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__CONNECT__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__disconnect__init(
    XiClientFtestFw__XiClientAPI__Disconnect *message) {
  static XiClientFtestFw__XiClientAPI__Disconnect init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__DISCONNECT__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__init(
    XiClientFtestFw__XiClientAPI__TopicAndQoS *message) {
  static XiClientFtestFw__XiClientAPI__TopicAndQoS init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____TOPIC_AND_QO_S__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__subscribe__init(
    XiClientFtestFw__XiClientAPI__Subscribe *message) {
  static XiClientFtestFw__XiClientAPI__Subscribe init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__SUBSCRIBE__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__publish_common_data__init(
    XiClientFtestFw__XiClientAPI__PublishCommonData *message) {
  static XiClientFtestFw__XiClientAPI__PublishCommonData init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_COMMON_DATA__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__publish_string__init(
    XiClientFtestFw__XiClientAPI__PublishString *message) {
  static XiClientFtestFw__XiClientAPI__PublishString init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_STRING__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__publish_binary__init(
    XiClientFtestFw__XiClientAPI__PublishBinary *message) {
  static XiClientFtestFw__XiClientAPI__PublishBinary init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_BINARY__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__publish_timeseries__init(
    XiClientFtestFw__XiClientAPI__PublishTimeseries *message) {
  static XiClientFtestFw__XiClientAPI__PublishTimeseries init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_TIMESERIES__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__init(
    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries *message) {
  static XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_FORMATTED_TIMESERIES__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__setup_tls__init(
    XiClientFtestFw__XiClientAPI__SetupTLS *message) {
  static XiClientFtestFw__XiClientAPI__SetupTLS init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__SETUP_TLS__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_api__init(
    XiClientFtestFw__XiClientAPI *message) {
  static XiClientFtestFw__XiClientAPI init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__INIT;
  *message = init_value;
}
size_t iotc_client_ftest_fw__iotc_client_api__get_packed_size(
    const XiClientFtestFw__XiClientAPI *message) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_api__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t iotc_client_ftest_fw__iotc_client_api__pack(
    const XiClientFtestFw__XiClientAPI *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_api__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t iotc_client_ftest_fw__iotc_client_api__pack_to_buffer(
    const XiClientFtestFw__XiClientAPI *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_api__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
XiClientFtestFw__XiClientAPI *iotc_client_ftest_fw__iotc_client_api__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (XiClientFtestFw__XiClientAPI *)protobuf_c_message_unpack(
      &iotc_client_ftest_fw__iotc_client_api__descriptor, allocator, len, data);
}
void iotc_client_ftest_fw__iotc_client_api__free_unpacked(
    XiClientFtestFw__XiClientAPI *message, ProtobufCAllocator *allocator) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_api__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__init(
    XiClientFtestFw__XiClientCallback__OnConnectFinish *message) {
  static XiClientFtestFw__XiClientCallback__OnConnectFinish init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_CONNECT_FINISH__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_callback__on_disconnect__init(
    XiClientFtestFw__XiClientCallback__OnDisconnect *message) {
  static XiClientFtestFw__XiClientCallback__OnDisconnect init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_DISCONNECT__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__init(
    XiClientFtestFw__XiClientCallback__OnSubscribeFinish *message) {
  static XiClientFtestFw__XiClientCallback__OnSubscribeFinish init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_SUBSCRIBE_FINISH__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_callback__on_message_received__init(
    XiClientFtestFw__XiClientCallback__OnMessageReceived *message) {
  static XiClientFtestFw__XiClientCallback__OnMessageReceived init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_MESSAGE_RECEIVED__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__init(
    XiClientFtestFw__XiClientCallback__OnPublishFinish *message) {
  static XiClientFtestFw__XiClientCallback__OnPublishFinish init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_PUBLISH_FINISH__INIT;
  *message = init_value;
}
void iotc_client_ftest_fw__iotc_client_callback__init(
    XiClientFtestFw__XiClientCallback *message) {
  static XiClientFtestFw__XiClientCallback init_value =
      IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__INIT;
  *message = init_value;
}
size_t iotc_client_ftest_fw__iotc_client_callback__get_packed_size(
    const XiClientFtestFw__XiClientCallback *message) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_callback__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t iotc_client_ftest_fw__iotc_client_callback__pack(
    const XiClientFtestFw__XiClientCallback *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_callback__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t iotc_client_ftest_fw__iotc_client_callback__pack_to_buffer(
    const XiClientFtestFw__XiClientCallback *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_callback__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
XiClientFtestFw__XiClientCallback *
iotc_client_ftest_fw__iotc_client_callback__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (XiClientFtestFw__XiClientCallback *)protobuf_c_message_unpack(
      &iotc_client_ftest_fw__iotc_client_callback__descriptor, allocator, len,
      data);
}
void iotc_client_ftest_fw__iotc_client_callback__free_unpacked(
    XiClientFtestFw__XiClientCallback *message, ProtobufCAllocator *allocator) {
  assert(message->base.descriptor ==
         &iotc_client_ftest_fw__iotc_client_callback__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api____server_address__field_descriptors
        [2] = {
            {
                "host", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_STRING,
                0, /* quantifier_offset */
                offsetof(XiClientFtestFw__XiClientAPI__ServerAddress, host),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "port", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientAPI__ServerAddress, has_port),
                offsetof(XiClientFtestFw__XiClientAPI__ServerAddress, port),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api____server_address__field_indices_by_name
        [] = {
            0, /* field[0] = host */
            1, /* field[1] = port */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api____server_address__number_ranges[1 +
                                                                           1] =
        {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api____server_address__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI._ServerAddress",
        "ServerAddress",
        "XiClientFtestFw__XiClientAPI__ServerAddress",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__ServerAddress),
        2,
        iotc_client_ftest_fw__iotc_client_api____server_address__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api____server_address__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api____server_address__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api____server_address__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const XiClientFtestFw__XiClientAPI__MqttSessionType
    iotc_client_ftest_fw__iotc_client_api__connect__mqtt_session_type__default_value =
        IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE__CLEAN_SESSION;
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__connect__field_descriptors[5] = {
        {
            "server_address", 1, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__Connect, server_address),
            &iotc_client_ftest_fw__iotc_client_api____server_address__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "username", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__Connect, username), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "password", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__Connect, password), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "mqtt_session_type", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(XiClientFtestFw__XiClientAPI__Connect,
                     has_mqtt_session_type),
            offsetof(XiClientFtestFw__XiClientAPI__Connect, mqtt_session_type),
            &iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__descriptor,
            &iotc_client_ftest_fw__iotc_client_api__connect__mqtt_session_type__default_value,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "connection_timeout", 5, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT32,
            offsetof(XiClientFtestFw__XiClientAPI__Connect,
                     has_connection_timeout),
            offsetof(XiClientFtestFw__XiClientAPI__Connect, connection_timeout),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__connect__field_indices_by_name[] = {
        4, /* field[4] = connection_timeout */
        3, /* field[3] = mqtt_session_type */
        2, /* field[2] = password */
        0, /* field[0] = server_address */
        1, /* field[1] = username */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__connect__number_ranges[1 + 1] = {
        {1, 0}, {0, 5}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__connect__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.Connect",
        "Connect",
        "XiClientFtestFw__XiClientAPI__Connect",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__Connect),
        5,
        iotc_client_ftest_fw__iotc_client_api__connect__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__connect__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__connect__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__connect__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
#define iotc_client_ftest_fw__iotc_client_api__disconnect__field_descriptors \
  NULL
#define iotc_client_ftest_fw__iotc_client_api__disconnect__field_indices_by_name \
  NULL
#define iotc_client_ftest_fw__iotc_client_api__disconnect__number_ranges NULL
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__disconnect__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.Disconnect",
        "Disconnect",
        "XiClientFtestFw__XiClientAPI__Disconnect",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__Disconnect),
        0,
        iotc_client_ftest_fw__iotc_client_api__disconnect__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__disconnect__field_indices_by_name,
        0,
        iotc_client_ftest_fw__iotc_client_api__disconnect__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__disconnect__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__field_descriptors
        [2] = {
            {
                "topic_name", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
                offsetof(XiClientFtestFw__XiClientAPI__TopicAndQoS, topic_name),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "qos", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientAPI__TopicAndQoS, has_qos),
                offsetof(XiClientFtestFw__XiClientAPI__TopicAndQoS, qos), NULL,
                NULL, 0,      /* flags */
                0, NULL, NULL /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__field_indices_by_name
        [] = {
            1, /* field[1] = qos */
            0, /* field[0] = topic_name */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__number_ranges[1 +
                                                                           1] =
        {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI._TopicAndQoS",
        "TopicAndQoS",
        "XiClientFtestFw__XiClientAPI__TopicAndQoS",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__TopicAndQoS),
        2,
        iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__subscribe__field_descriptors[1] = {
        {
            "topic_qos_list", 1, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(XiClientFtestFw__XiClientAPI__Subscribe, n_topic_qos_list),
            offsetof(XiClientFtestFw__XiClientAPI__Subscribe, topic_qos_list),
            &iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__subscribe__field_indices_by_name[] =
        {
            0, /* field[0] = topic_qos_list */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__subscribe__number_ranges[1 + 1] = {
        {1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__subscribe__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.Subscribe",
        "Subscribe",
        "XiClientFtestFw__XiClientAPI__Subscribe",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__Subscribe),
        1,
        iotc_client_ftest_fw__iotc_client_api__subscribe__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__subscribe__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__subscribe__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__subscribe__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_common_data__field_descriptors
        [2] = {
            {
                "topic_name", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
                offsetof(XiClientFtestFw__XiClientAPI__PublishCommonData,
                         topic_name),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "qos", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientAPI__PublishCommonData,
                         has_qos),
                offsetof(XiClientFtestFw__XiClientAPI__PublishCommonData, qos),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__publish_common_data__field_indices_by_name
        [] = {
            1, /* field[1] = qos */
            0, /* field[0] = topic_name */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__publish_common_data__number_ranges
        [1 + 1] = {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.PublishCommonData",
        "PublishCommonData",
        "XiClientFtestFw__XiClientAPI__PublishCommonData",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__PublishCommonData),
        2,
        iotc_client_ftest_fw__iotc_client_api__publish_common_data__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__publish_common_data__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__publish_common_data__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__publish_common_data__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_string__field_descriptors[3] = {
        {
            "publish_common_data", 1, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__PublishString,
                     publish_common_data),
            &iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "payload", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__PublishString, payload),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "retain", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(XiClientFtestFw__XiClientAPI__PublishString, has_retain),
            offsetof(XiClientFtestFw__XiClientAPI__PublishString, retain), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__publish_string__field_indices_by_name
        [] = {
            1, /* field[1] = payload */
            0, /* field[0] = publish_common_data */
            2, /* field[2] = retain */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__publish_string__number_ranges[1 +
                                                                         1] = {
        {1, 0}, {0, 3}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_string__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.PublishString",
        "PublishString",
        "XiClientFtestFw__XiClientAPI__PublishString",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__PublishString),
        3,
        iotc_client_ftest_fw__iotc_client_api__publish_string__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__publish_string__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__publish_string__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__publish_string__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_binary__field_descriptors[3] = {
        {
            "publish_common_data", 1, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__PublishBinary,
                     publish_common_data),
            &iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "payload", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BYTES,
            offsetof(XiClientFtestFw__XiClientAPI__PublishBinary, has_payload),
            offsetof(XiClientFtestFw__XiClientAPI__PublishBinary, payload),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "retain", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(XiClientFtestFw__XiClientAPI__PublishBinary, has_retain),
            offsetof(XiClientFtestFw__XiClientAPI__PublishBinary, retain), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__publish_binary__field_indices_by_name
        [] = {
            1, /* field[1] = payload */
            0, /* field[0] = publish_common_data */
            2, /* field[2] = retain */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__publish_binary__number_ranges[1 +
                                                                         1] = {
        {1, 0}, {0, 3}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_binary__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.PublishBinary",
        "PublishBinary",
        "XiClientFtestFw__XiClientAPI__PublishBinary",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__PublishBinary),
        3,
        iotc_client_ftest_fw__iotc_client_api__publish_binary__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__publish_binary__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__publish_binary__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__publish_binary__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_timeseries__field_descriptors
        [2] = {
            {
                "publish_common_data", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
                offsetof(XiClientFtestFw__XiClientAPI__PublishTimeseries,
                         publish_common_data),
                &iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor,
                NULL, 0,      /* flags */
                0, NULL, NULL /* reserved1,reserved2, etc */
            },
            {
                "payload", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_FLOAT,
                offsetof(XiClientFtestFw__XiClientAPI__PublishTimeseries,
                         has_payload),
                offsetof(XiClientFtestFw__XiClientAPI__PublishTimeseries,
                         payload),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__publish_timeseries__field_indices_by_name
        [] = {
            1, /* field[1] = payload */
            0, /* field[0] = publish_common_data */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__publish_timeseries__number_ranges
        [1 + 1] = {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_timeseries__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.PublishTimeseries",
        "PublishTimeseries",
        "XiClientFtestFw__XiClientAPI__PublishTimeseries",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__PublishTimeseries),
        2,
        iotc_client_ftest_fw__iotc_client_api__publish_timeseries__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__publish_timeseries__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__publish_timeseries__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__publish_timeseries__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__field_descriptors
        [5] = {
            {
                "publish_common_data", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    publish_common_data),
                &iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor,
                NULL, 0,      /* flags */
                0, NULL, NULL /* reserved1,reserved2, etc */
            },
            {
                "time", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    has_time),
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    time),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "category", 3, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    category),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "string_value", 4, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    string_value),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "numeric_value", 5, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_FLOAT,
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    has_numeric_value),
                offsetof(
                    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries,
                    numeric_value),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__field_indices_by_name
        [] = {
            2, /* field[2] = category */
            4, /* field[4] = numeric_value */
            0, /* field[0] = publish_common_data */
            3, /* field[3] = string_value */
            1, /* field[1] = time */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__number_ranges
        [1 + 1] = {{1, 0}, {0, 5}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.PublishFormattedTimeseries",
        "PublishFormattedTimeseries",
        "XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries),
        5,
        iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__setup_tls__field_descriptors[1] = {
        {
            "ca_cert_file", 1, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI__SetupTLS, ca_cert_file),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__setup_tls__field_indices_by_name[] =
        {
            0, /* field[0] = ca_cert_file */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__setup_tls__number_ranges[1 + 1] = {
        {1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__setup_tls__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI.SetupTLS",
        "SetupTLS",
        "XiClientFtestFw__XiClientAPI__SetupTLS",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI__SetupTLS),
        1,
        iotc_client_ftest_fw__iotc_client_api__setup_tls__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__setup_tls__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__setup_tls__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_api__setup_tls__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCEnumValue
    iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__enum_values_by_number
        [2] = {
            {"UNCLEAN_SESSION",
             "IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE__"
             "UNCLEAN_SESSION",
             0},
            {"CLEAN_SESSION",
             "IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE__"
             "CLEAN_SESSION",
             1},
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__value_ranges[] =
        {{0, 0}, {0, 2}};
static const ProtobufCEnumValueIndex
    iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__enum_values_by_name
        [2] = {
            {"CLEAN_SESSION", 1},
            {"UNCLEAN_SESSION", 0},
};
const ProtobufCEnumDescriptor
    iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__descriptor = {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI._MqttSessionType",
        "_MqttSessionType",
        "XiClientFtestFw__XiClientAPI__MqttSessionType",
        "iotc_client_ftest_fw",
        2,
        iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__enum_values_by_number,
        2,
        iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__enum_values_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__value_ranges,
        NULL,
        NULL,
        NULL,
        NULL /* reserved[1234] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_api__field_descriptors[8] = {
        {
            "connect", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_MESSAGE,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, connect),
            &iotc_client_ftest_fw__iotc_client_api__connect__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "disconnect", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_MESSAGE,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, disconnect),
            &iotc_client_ftest_fw__iotc_client_api__disconnect__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "subscribe", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_MESSAGE,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, subscribe),
            &iotc_client_ftest_fw__iotc_client_api__subscribe__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "publish_string", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, publish_string),
            &iotc_client_ftest_fw__iotc_client_api__publish_string__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "publish_binary", 5, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, publish_binary),
            &iotc_client_ftest_fw__iotc_client_api__publish_binary__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "publish_timeseries", 6, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, publish_timeseries),
            &iotc_client_ftest_fw__iotc_client_api__publish_timeseries__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "publish_formatted_timeseries", 7, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI,
                     publish_formatted_timeseries),
            &iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "setup_tls", 8, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_MESSAGE,
            0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientAPI, setup_tls),
            &iotc_client_ftest_fw__iotc_client_api__setup_tls__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_api__field_indices_by_name[] = {
        0, /* field[0] = connect */
        1, /* field[1] = disconnect */
        4, /* field[4] = publish_binary */
        6, /* field[6] = publish_formatted_timeseries */
        3, /* field[3] = publish_string */
        5, /* field[5] = publish_timeseries */
        7, /* field[7] = setup_tls */
        2, /* field[2] = subscribe */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_api__number_ranges[1 + 1] = {{1, 0},
                                                                   {0, 8}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientAPI",
        "XiClientAPI",
        "XiClientFtestFw__XiClientAPI",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientAPI),
        8,
        iotc_client_ftest_fw__iotc_client_api__field_descriptors,
        iotc_client_ftest_fw__iotc_client_api__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_api__number_ranges,
        (ProtobufCMessageInit)iotc_client_ftest_fw__iotc_client_api__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__field_descriptors
        [1] = {
            {
                "connect_result", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientCallback__OnConnectFinish,
                         has_connect_result),
                offsetof(XiClientFtestFw__XiClientCallback__OnConnectFinish,
                         connect_result),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__field_indices_by_name
        [] = {
            0, /* field[0] = connect_result */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__number_ranges
        [1 + 1] = {{1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientCallback.OnConnectFinish",
        "OnConnectFinish",
        "XiClientFtestFw__XiClientCallback__OnConnectFinish",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientCallback__OnConnectFinish),
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__field_descriptors,
        iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_disconnect__field_descriptors
        [1] = {
            {
                "error_code", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientCallback__OnDisconnect,
                         has_error_code),
                offsetof(XiClientFtestFw__XiClientCallback__OnDisconnect,
                         error_code),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_callback__on_disconnect__field_indices_by_name
        [] = {
            0, /* field[0] = error_code */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_callback__on_disconnect__number_ranges
        [1 + 1] = {{1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_disconnect__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientCallback.OnDisconnect",
        "OnDisconnect",
        "XiClientFtestFw__XiClientCallback__OnDisconnect",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientCallback__OnDisconnect),
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_disconnect__field_descriptors,
        iotc_client_ftest_fw__iotc_client_callback__on_disconnect__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_disconnect__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_callback__on_disconnect__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__field_descriptors
        [1] = {
            {
                "subscribe_result_list", 1, PROTOBUF_C_LABEL_REPEATED,
                PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientCallback__OnSubscribeFinish,
                         n_subscribe_result_list),
                offsetof(XiClientFtestFw__XiClientCallback__OnSubscribeFinish,
                         subscribe_result_list),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__field_indices_by_name
        [] = {
            0, /* field[0] = subscribe_result_list */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__number_ranges
        [1 + 1] = {{1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientCallback.OnSubscribeFinish",
        "OnSubscribeFinish",
        "XiClientFtestFw__XiClientCallback__OnSubscribeFinish",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientCallback__OnSubscribeFinish),
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__field_descriptors,
        iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_message_received__field_descriptors
        [3] = {
            {
                "topic_name", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
                offsetof(XiClientFtestFw__XiClientCallback__OnMessageReceived,
                         topic_name),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "qos", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientCallback__OnMessageReceived,
                         has_qos),
                offsetof(XiClientFtestFw__XiClientCallback__OnMessageReceived,
                         qos),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
            {
                "payload", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BYTES,
                offsetof(XiClientFtestFw__XiClientCallback__OnMessageReceived,
                         has_payload),
                offsetof(XiClientFtestFw__XiClientCallback__OnMessageReceived,
                         payload),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_callback__on_message_received__field_indices_by_name
        [] = {
            2, /* field[2] = payload */
            1, /* field[1] = qos */
            0, /* field[0] = topic_name */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_callback__on_message_received__number_ranges
        [1 + 1] = {{1, 0}, {0, 3}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_message_received__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientCallback.OnMessageReceived",
        "OnMessageReceived",
        "XiClientFtestFw__XiClientCallback__OnMessageReceived",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientCallback__OnMessageReceived),
        3,
        iotc_client_ftest_fw__iotc_client_callback__on_message_received__field_descriptors,
        iotc_client_ftest_fw__iotc_client_callback__on_message_received__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_message_received__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_callback__on_message_received__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__field_descriptors
        [1] = {
            {
                "return_code", 1, PROTOBUF_C_LABEL_OPTIONAL,
                PROTOBUF_C_TYPE_UINT32,
                offsetof(XiClientFtestFw__XiClientCallback__OnPublishFinish,
                         has_return_code),
                offsetof(XiClientFtestFw__XiClientCallback__OnPublishFinish,
                         return_code),
                NULL, NULL, 0, /* flags */
                0, NULL, NULL  /* reserved1,reserved2, etc */
            },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__field_indices_by_name
        [] = {
            0, /* field[0] = return_code */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__number_ranges
        [1 + 1] = {{1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientCallback.OnPublishFinish",
        "OnPublishFinish",
        "XiClientFtestFw__XiClientCallback__OnPublishFinish",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientCallback__OnPublishFinish),
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__field_descriptors,
        iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__number_ranges,
        (ProtobufCMessageInit)
            iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    iotc_client_ftest_fw__iotc_client_callback__field_descriptors[5] = {
        {
            "on_connect_finish", 1, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientCallback, on_connect_finish),
            &iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "on_disconnect", 2, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientCallback, on_disconnect),
            &iotc_client_ftest_fw__iotc_client_callback__on_disconnect__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "on_subscribe_finish", 3, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientCallback, on_subscribe_finish),
            &iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "on_message_received", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientCallback, on_message_received),
            &iotc_client_ftest_fw__iotc_client_callback__on_message_received__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "on_publish_finish", 5, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(XiClientFtestFw__XiClientCallback, on_publish_finish),
            &iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    iotc_client_ftest_fw__iotc_client_callback__field_indices_by_name[] = {
        0, /* field[0] = on_connect_finish */
        1, /* field[1] = on_disconnect */
        3, /* field[3] = on_message_received */
        4, /* field[4] = on_publish_finish */
        2, /* field[2] = on_subscribe_finish */
};
static const ProtobufCIntRange
    iotc_client_ftest_fw__iotc_client_callback__number_ranges[1 + 1] = {{1, 0},
                                                                        {0, 5}};
const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "iotc_client_ftest_fw.XiClientCallback",
        "XiClientCallback",
        "XiClientFtestFw__XiClientCallback",
        "iotc_client_ftest_fw",
        sizeof(XiClientFtestFw__XiClientCallback),
        5,
        iotc_client_ftest_fw__iotc_client_callback__field_descriptors,
        iotc_client_ftest_fw__iotc_client_callback__field_indices_by_name,
        1,
        iotc_client_ftest_fw__iotc_client_callback__number_ranges,
        (ProtobufCMessageInit)iotc_client_ftest_fw__iotc_client_callback__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
