/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iotc_control_channel_protocol.proto */

#ifndef PROTOBUF_C_iotc_5fcontrol_5fchannel_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_C_iotc_5fcontrol_5fchannel_5fprotocol_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _XiClientFtestFw__XiClientAPI XiClientFtestFw__XiClientAPI;
typedef struct _XiClientFtestFw__XiClientAPI__ServerAddress
    XiClientFtestFw__XiClientAPI__ServerAddress;
typedef struct _XiClientFtestFw__XiClientAPI__Connect
    XiClientFtestFw__XiClientAPI__Connect;
typedef struct _XiClientFtestFw__XiClientAPI__Disconnect
    XiClientFtestFw__XiClientAPI__Disconnect;
typedef struct _XiClientFtestFw__XiClientAPI__TopicAndQoS
    XiClientFtestFw__XiClientAPI__TopicAndQoS;
typedef struct _XiClientFtestFw__XiClientAPI__Subscribe
    XiClientFtestFw__XiClientAPI__Subscribe;
typedef struct _XiClientFtestFw__XiClientAPI__PublishCommonData
    XiClientFtestFw__XiClientAPI__PublishCommonData;
typedef struct _XiClientFtestFw__XiClientAPI__PublishString
    XiClientFtestFw__XiClientAPI__PublishString;
typedef struct _XiClientFtestFw__XiClientAPI__PublishBinary
    XiClientFtestFw__XiClientAPI__PublishBinary;
typedef struct _XiClientFtestFw__XiClientAPI__PublishTimeseries
    XiClientFtestFw__XiClientAPI__PublishTimeseries;
typedef struct _XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries
    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries;
typedef struct _XiClientFtestFw__XiClientAPI__SetupTLS
    XiClientFtestFw__XiClientAPI__SetupTLS;
typedef struct _XiClientFtestFw__XiClientCallback
    XiClientFtestFw__XiClientCallback;
typedef struct _XiClientFtestFw__XiClientCallback__OnConnectFinish
    XiClientFtestFw__XiClientCallback__OnConnectFinish;
typedef struct _XiClientFtestFw__XiClientCallback__OnDisconnect
    XiClientFtestFw__XiClientCallback__OnDisconnect;
typedef struct _XiClientFtestFw__XiClientCallback__OnSubscribeFinish
    XiClientFtestFw__XiClientCallback__OnSubscribeFinish;
typedef struct _XiClientFtestFw__XiClientCallback__OnMessageReceived
    XiClientFtestFw__XiClientCallback__OnMessageReceived;
typedef struct _XiClientFtestFw__XiClientCallback__OnPublishFinish
    XiClientFtestFw__XiClientCallback__OnPublishFinish;

/* --- enums --- */

typedef enum _XiClientFtestFw__XiClientAPI__MqttSessionType {
  IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE__UNCLEAN_SESSION =
      0,
  IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE__CLEAN_SESSION =
      1 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(
          IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE)
} XiClientFtestFw__XiClientAPI__MqttSessionType;

/* --- messages --- */

struct _XiClientFtestFw__XiClientAPI__ServerAddress {
  ProtobufCMessage base;
  char *host;
  protobuf_c_boolean has_port;
  uint32_t port;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____SERVER_ADDRESS__INIT         \
  {                                                                           \
    PROTOBUF_C_MESSAGE_INIT(                                                  \
        &iotc_client_ftest_fw__iotc_client_api____server_address__descriptor) \
    , NULL, 0, 0                                                              \
  }

struct _XiClientFtestFw__XiClientAPI__Connect {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientAPI__ServerAddress *server_address;
  char *username;
  char *password;
  protobuf_c_boolean has_mqtt_session_type;
  XiClientFtestFw__XiClientAPI__MqttSessionType mqtt_session_type;
  protobuf_c_boolean has_connection_timeout;
  uint32_t connection_timeout;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__CONNECT__INIT                       \
  {                                                                                \
    PROTOBUF_C_MESSAGE_INIT(                                                       \
        &iotc_client_ftest_fw__iotc_client_api__connect__descriptor)               \
    , NULL, NULL, NULL, 0,                                                         \
        IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____MQTT_SESSION_TYPE__CLEAN_SESSION, \
        0, 0                                                                       \
  }

struct _XiClientFtestFw__XiClientAPI__Disconnect {
  ProtobufCMessage base;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__DISCONNECT__INIT         \
  {                                                                     \
    PROTOBUF_C_MESSAGE_INIT(                                            \
        &iotc_client_ftest_fw__iotc_client_api__disconnect__descriptor) \
  }

struct _XiClientFtestFw__XiClientAPI__TopicAndQoS {
  ProtobufCMessage base;
  char *topic_name;
  protobuf_c_boolean has_qos;
  uint32_t qos;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API____TOPIC_AND_QO_S__INIT         \
  {                                                                           \
    PROTOBUF_C_MESSAGE_INIT(                                                  \
        &iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__descriptor) \
    , NULL, 0, 0                                                              \
  }

struct _XiClientFtestFw__XiClientAPI__Subscribe {
  ProtobufCMessage base;
  size_t n_topic_qos_list;
  XiClientFtestFw__XiClientAPI__TopicAndQoS **topic_qos_list;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__SUBSCRIBE__INIT         \
  {                                                                    \
    PROTOBUF_C_MESSAGE_INIT(                                           \
        &iotc_client_ftest_fw__iotc_client_api__subscribe__descriptor) \
    , 0, NULL                                                          \
  }

struct _XiClientFtestFw__XiClientAPI__PublishCommonData {
  ProtobufCMessage base;
  char *topic_name;
  protobuf_c_boolean has_qos;
  uint32_t qos;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_COMMON_DATA__INIT         \
  {                                                                              \
    PROTOBUF_C_MESSAGE_INIT(                                                     \
        &iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor) \
    , NULL, 0, 0                                                                 \
  }

struct _XiClientFtestFw__XiClientAPI__PublishString {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientAPI__PublishCommonData *publish_common_data;
  char *payload;
  protobuf_c_boolean has_retain;
  uint32_t retain;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_STRING__INIT         \
  {                                                                         \
    PROTOBUF_C_MESSAGE_INIT(                                                \
        &iotc_client_ftest_fw__iotc_client_api__publish_string__descriptor) \
    , NULL, NULL, 0, 0                                                      \
  }

struct _XiClientFtestFw__XiClientAPI__PublishBinary {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientAPI__PublishCommonData *publish_common_data;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
  protobuf_c_boolean has_retain;
  uint32_t retain;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_BINARY__INIT         \
  {                                                                         \
    PROTOBUF_C_MESSAGE_INIT(                                                \
        &iotc_client_ftest_fw__iotc_client_api__publish_binary__descriptor) \
    , NULL, 0, {0, NULL}, 0, 0                                              \
  }

struct _XiClientFtestFw__XiClientAPI__PublishTimeseries {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientAPI__PublishCommonData *publish_common_data;
  protobuf_c_boolean has_payload;
  float payload;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_TIMESERIES__INIT         \
  {                                                                             \
    PROTOBUF_C_MESSAGE_INIT(                                                    \
        &iotc_client_ftest_fw__iotc_client_api__publish_timeseries__descriptor) \
    , NULL, 0, 0                                                                \
  }

struct _XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientAPI__PublishCommonData *publish_common_data;
  protobuf_c_boolean has_time;
  uint32_t time;
  char *category;
  char *string_value;
  protobuf_c_boolean has_numeric_value;
  float numeric_value;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__PUBLISH_FORMATTED_TIMESERIES__INIT         \
  {                                                                                       \
    PROTOBUF_C_MESSAGE_INIT(                                                              \
        &iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__descriptor) \
    , NULL, 0, 0, NULL, NULL, 0, 0                                                        \
  }

struct _XiClientFtestFw__XiClientAPI__SetupTLS {
  ProtobufCMessage base;
  char *ca_cert_file;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__SETUP_TLS__INIT         \
  {                                                                    \
    PROTOBUF_C_MESSAGE_INIT(                                           \
        &iotc_client_ftest_fw__iotc_client_api__setup_tls__descriptor) \
    , NULL                                                             \
  }

struct _XiClientFtestFw__XiClientAPI {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientAPI__Connect *connect;
  XiClientFtestFw__XiClientAPI__Disconnect *disconnect;
  XiClientFtestFw__XiClientAPI__Subscribe *subscribe;
  XiClientFtestFw__XiClientAPI__PublishString *publish_string;
  XiClientFtestFw__XiClientAPI__PublishBinary *publish_binary;
  XiClientFtestFw__XiClientAPI__PublishTimeseries *publish_timeseries;
  XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries
      *publish_formatted_timeseries;
  XiClientFtestFw__XiClientAPI__SetupTLS *setup_tls;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_API__INIT         \
  {                                                         \
    PROTOBUF_C_MESSAGE_INIT(                                \
        &iotc_client_ftest_fw__iotc_client_api__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL        \
  }

struct _XiClientFtestFw__XiClientCallback__OnConnectFinish {
  ProtobufCMessage base;
  protobuf_c_boolean has_connect_result;
  uint32_t connect_result;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_CONNECT_FINISH__INIT         \
  {                                                                                 \
    PROTOBUF_C_MESSAGE_INIT(                                                        \
        &iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__descriptor) \
    , 0, 0                                                                          \
  }

struct _XiClientFtestFw__XiClientCallback__OnDisconnect {
  ProtobufCMessage base;
  protobuf_c_boolean has_error_code;
  uint32_t error_code;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_DISCONNECT__INIT         \
  {                                                                             \
    PROTOBUF_C_MESSAGE_INIT(                                                    \
        &iotc_client_ftest_fw__iotc_client_callback__on_disconnect__descriptor) \
    , 0, 0                                                                      \
  }

struct _XiClientFtestFw__XiClientCallback__OnSubscribeFinish {
  ProtobufCMessage base;
  size_t n_subscribe_result_list;
  uint32_t *subscribe_result_list;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_SUBSCRIBE_FINISH__INIT         \
  {                                                                                   \
    PROTOBUF_C_MESSAGE_INIT(                                                          \
        &iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__descriptor) \
    , 0, NULL                                                                         \
  }

struct _XiClientFtestFw__XiClientCallback__OnMessageReceived {
  ProtobufCMessage base;
  char *topic_name;
  protobuf_c_boolean has_qos;
  uint32_t qos;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_MESSAGE_RECEIVED__INIT         \
  {                                                                                   \
    PROTOBUF_C_MESSAGE_INIT(                                                          \
        &iotc_client_ftest_fw__iotc_client_callback__on_message_received__descriptor) \
    , NULL, 0, 0, 0, { 0, NULL }                                                      \
  }

struct _XiClientFtestFw__XiClientCallback__OnPublishFinish {
  ProtobufCMessage base;
  protobuf_c_boolean has_return_code;
  uint32_t return_code;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__ON_PUBLISH_FINISH__INIT         \
  {                                                                                 \
    PROTOBUF_C_MESSAGE_INIT(                                                        \
        &iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__descriptor) \
    , 0, 0                                                                          \
  }

struct _XiClientFtestFw__XiClientCallback {
  ProtobufCMessage base;
  XiClientFtestFw__XiClientCallback__OnConnectFinish *on_connect_finish;
  XiClientFtestFw__XiClientCallback__OnDisconnect *on_disconnect;
  XiClientFtestFw__XiClientCallback__OnSubscribeFinish *on_subscribe_finish;
  XiClientFtestFw__XiClientCallback__OnMessageReceived *on_message_received;
  XiClientFtestFw__XiClientCallback__OnPublishFinish *on_publish_finish;
};
#define IOTC_CLIENT_FTEST_FW__IOTC_CLIENT_CALLBACK__INIT         \
  {                                                              \
    PROTOBUF_C_MESSAGE_INIT(                                     \
        &iotc_client_ftest_fw__iotc_client_callback__descriptor) \
    , NULL, NULL, NULL, NULL, NULL                               \
  }

/* XiClientFtestFw__XiClientAPI__ServerAddress methods */
void iotc_client_ftest_fw__iotc_client_api____server_address__init(
    XiClientFtestFw__XiClientAPI__ServerAddress *message);
/* XiClientFtestFw__XiClientAPI__Connect methods */
void iotc_client_ftest_fw__iotc_client_api__connect__init(
    XiClientFtestFw__XiClientAPI__Connect *message);
/* XiClientFtestFw__XiClientAPI__Disconnect methods */
void iotc_client_ftest_fw__iotc_client_api__disconnect__init(
    XiClientFtestFw__XiClientAPI__Disconnect *message);
/* XiClientFtestFw__XiClientAPI__TopicAndQoS methods */
void iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__init(
    XiClientFtestFw__XiClientAPI__TopicAndQoS *message);
/* XiClientFtestFw__XiClientAPI__Subscribe methods */
void iotc_client_ftest_fw__iotc_client_api__subscribe__init(
    XiClientFtestFw__XiClientAPI__Subscribe *message);
/* XiClientFtestFw__XiClientAPI__PublishCommonData methods */
void iotc_client_ftest_fw__iotc_client_api__publish_common_data__init(
    XiClientFtestFw__XiClientAPI__PublishCommonData *message);
/* XiClientFtestFw__XiClientAPI__PublishString methods */
void iotc_client_ftest_fw__iotc_client_api__publish_string__init(
    XiClientFtestFw__XiClientAPI__PublishString *message);
/* XiClientFtestFw__XiClientAPI__PublishBinary methods */
void iotc_client_ftest_fw__iotc_client_api__publish_binary__init(
    XiClientFtestFw__XiClientAPI__PublishBinary *message);
/* XiClientFtestFw__XiClientAPI__PublishTimeseries methods */
void iotc_client_ftest_fw__iotc_client_api__publish_timeseries__init(
    XiClientFtestFw__XiClientAPI__PublishTimeseries *message);
/* XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries methods */
void iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__init(
    XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries *message);
/* XiClientFtestFw__XiClientAPI__SetupTLS methods */
void iotc_client_ftest_fw__iotc_client_api__setup_tls__init(
    XiClientFtestFw__XiClientAPI__SetupTLS *message);
/* XiClientFtestFw__XiClientAPI methods */
void iotc_client_ftest_fw__iotc_client_api__init(
    XiClientFtestFw__XiClientAPI *message);
size_t iotc_client_ftest_fw__iotc_client_api__get_packed_size(
    const XiClientFtestFw__XiClientAPI *message);
size_t iotc_client_ftest_fw__iotc_client_api__pack(
    const XiClientFtestFw__XiClientAPI *message, uint8_t *out);
size_t iotc_client_ftest_fw__iotc_client_api__pack_to_buffer(
    const XiClientFtestFw__XiClientAPI *message, ProtobufCBuffer *buffer);
XiClientFtestFw__XiClientAPI *iotc_client_ftest_fw__iotc_client_api__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void iotc_client_ftest_fw__iotc_client_api__free_unpacked(
    XiClientFtestFw__XiClientAPI *message, ProtobufCAllocator *allocator);
/* XiClientFtestFw__XiClientCallback__OnConnectFinish methods */
void iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__init(
    XiClientFtestFw__XiClientCallback__OnConnectFinish *message);
/* XiClientFtestFw__XiClientCallback__OnDisconnect methods */
void iotc_client_ftest_fw__iotc_client_callback__on_disconnect__init(
    XiClientFtestFw__XiClientCallback__OnDisconnect *message);
/* XiClientFtestFw__XiClientCallback__OnSubscribeFinish methods */
void iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__init(
    XiClientFtestFw__XiClientCallback__OnSubscribeFinish *message);
/* XiClientFtestFw__XiClientCallback__OnMessageReceived methods */
void iotc_client_ftest_fw__iotc_client_callback__on_message_received__init(
    XiClientFtestFw__XiClientCallback__OnMessageReceived *message);
/* XiClientFtestFw__XiClientCallback__OnPublishFinish methods */
void iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__init(
    XiClientFtestFw__XiClientCallback__OnPublishFinish *message);
/* XiClientFtestFw__XiClientCallback methods */
void iotc_client_ftest_fw__iotc_client_callback__init(
    XiClientFtestFw__XiClientCallback *message);
size_t iotc_client_ftest_fw__iotc_client_callback__get_packed_size(
    const XiClientFtestFw__XiClientCallback *message);
size_t iotc_client_ftest_fw__iotc_client_callback__pack(
    const XiClientFtestFw__XiClientCallback *message, uint8_t *out);
size_t iotc_client_ftest_fw__iotc_client_callback__pack_to_buffer(
    const XiClientFtestFw__XiClientCallback *message, ProtobufCBuffer *buffer);
XiClientFtestFw__XiClientCallback *
iotc_client_ftest_fw__iotc_client_callback__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void iotc_client_ftest_fw__iotc_client_callback__free_unpacked(
    XiClientFtestFw__XiClientCallback *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*XiClientFtestFw__XiClientAPI__ServerAddress_Closure)(
    const XiClientFtestFw__XiClientAPI__ServerAddress *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__Connect_Closure)(
    const XiClientFtestFw__XiClientAPI__Connect *message, void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__Disconnect_Closure)(
    const XiClientFtestFw__XiClientAPI__Disconnect *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__TopicAndQoS_Closure)(
    const XiClientFtestFw__XiClientAPI__TopicAndQoS *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__Subscribe_Closure)(
    const XiClientFtestFw__XiClientAPI__Subscribe *message, void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__PublishCommonData_Closure)(
    const XiClientFtestFw__XiClientAPI__PublishCommonData *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__PublishString_Closure)(
    const XiClientFtestFw__XiClientAPI__PublishString *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__PublishBinary_Closure)(
    const XiClientFtestFw__XiClientAPI__PublishBinary *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__PublishTimeseries_Closure)(
    const XiClientFtestFw__XiClientAPI__PublishTimeseries *message,
    void *closure_data);
typedef void (
    *XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries_Closure)(
    const XiClientFtestFw__XiClientAPI__PublishFormattedTimeseries *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI__SetupTLS_Closure)(
    const XiClientFtestFw__XiClientAPI__SetupTLS *message, void *closure_data);
typedef void (*XiClientFtestFw__XiClientAPI_Closure)(
    const XiClientFtestFw__XiClientAPI *message, void *closure_data);
typedef void (*XiClientFtestFw__XiClientCallback__OnConnectFinish_Closure)(
    const XiClientFtestFw__XiClientCallback__OnConnectFinish *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientCallback__OnDisconnect_Closure)(
    const XiClientFtestFw__XiClientCallback__OnDisconnect *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientCallback__OnSubscribeFinish_Closure)(
    const XiClientFtestFw__XiClientCallback__OnSubscribeFinish *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientCallback__OnMessageReceived_Closure)(
    const XiClientFtestFw__XiClientCallback__OnMessageReceived *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientCallback__OnPublishFinish_Closure)(
    const XiClientFtestFw__XiClientCallback__OnPublishFinish *message,
    void *closure_data);
typedef void (*XiClientFtestFw__XiClientCallback_Closure)(
    const XiClientFtestFw__XiClientCallback *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api____server_address__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__connect__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__disconnect__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api____topic_and_qo_s__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__subscribe__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_common_data__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_string__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_binary__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_timeseries__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__publish_formatted_timeseries__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_api__setup_tls__descriptor;
extern const ProtobufCEnumDescriptor
    iotc_client_ftest_fw__iotc_client_api____mqtt_session_type__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_connect_finish__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_disconnect__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_subscribe_finish__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_message_received__descriptor;
extern const ProtobufCMessageDescriptor
    iotc_client_ftest_fw__iotc_client_callback__on_publish_finish__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_iotc_5fcontrol_5fchannel_5fprotocol_2eproto__INCLUDED */
