name: POSIX Builds

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo'
        default: 'bar'
        required: false

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - run: |
          expect res/travis/travis_build_mbedtls.expect IOTC_DEBUG_OUTPUT=0
