name: POSIX Builds

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo'
        default: 'bar'
        required: false

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - run: |
          sudo apt-get update
          sudo apt-get install expect
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          expect res/travis/travis_build_mbedtls.expect make IOTC_DEBUG_OUTPUT=0
