name: POSIX Builds

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo'
        default: 'bar'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [POSIX_DEV, POSIX_DEV_MIN, POSIX_REL, POSIX_REL_MIN, POSIX_THREADING_REL]
        tls: [mbedtls] 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Submodule update
        shell: bash
        run: |
          set -e
          git submodule init
          git submodule update

      - name: Update apt
        shell: bash
        run: sudo apt-get update

      - name: Install Prereqs
        run: |
          set -e
          sudo apt-get install expect
          # sudo apt-get install clang-3.8
          # sudo apt-get qemu-system
          # sudo apt-get libc6:i386
          # sudo apt-get libc6-dev-i386
          # sudo apt-get gcc-multilib
          # sudo apt-get linux-libc-dev:i386
          # sudo apt-get device-tree-compiler
          # sudo apt-get gperf
          # sudo apt-get dfu-util
          # sudo apt-get xz-utils
          # sudo apt-get python3-pip

      - name: Debug Dirs third_party
        shell: bash
        run: |
          ls -l third_party/

      - name: Debug Dirs third_party/googletest
        shell: bash
        run: |
          ls third_party/googletest/
          
      - name: build
        run: |
          expect res/travis/travis_build_mbedtls.expect make PRESET=${{ matrix.python_version }}
