name: POSIX Builds
workflow_dispatch:
  inputs:
    foo:
      description: 'placeholder'
      default: 'bar'
      required: 'false'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

